# Assignment : Numpy Assignment

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4', '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))


Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_ variable:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list variable:")
for element in array_list:
    print(type(element))


Data types of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list variable:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_ variable:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list variable:")
for element in array_list:
    print(type(element))


Data types of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list variable:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(
ii) size

In [7]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape

# Find the size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print("Array of zeros:")
print(zero_matrix)


Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
